/**
 * Cover Letter Generator
 * Generates a formal protest letter (1 page) — pre-filled, ready to sign and submit.
 * This is the 3rd PDF attachment alongside Quick Start Guide and Evidence Packet.
 */

export interface CoverLetterData {
  ownerName: string;       // "Property Owner" if unknown
  address: string;
  acct: string;
  county: string;          // "Harris", "Dallas", etc.
  state: string;           // "TX" or "IL"
  filingBody: string;      // "HCAD", "DCAD", etc.
  filingBodyFull: string;  // "Harris County Appraisal District"
  currentAssessment: number;
  fairAssessment: number;
  overAssessedPct: number;
  compCount: number;
  compMedianPerSqft: number;
  perSqft: number;
  taxYear: string;         // "2025"
}

export function generateCoverLetterHtml(data: CoverLetterData): string {
  const formatCurrency = (amount: number) =>
    new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', minimumFractionDigits: 0, maximumFractionDigits: 0 }).format(amount);

  const today = new Date();
  const dateStr = today.toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });

  const reduction = data.currentAssessment - data.fairAssessment;

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Protest Cover Letter</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    @page { size: letter; margin: 1in 1in; }
    body {
      font-family: 'Times New Roman', Times, Georgia, serif;
      font-size: 12pt;
      line-height: 1.6;
      color: #1a1a1a;
    }
    .date { margin-bottom: 24pt; }
    .recipient { margin-bottom: 24pt; }
    .subject {
      margin-bottom: 18pt;
      font-weight: bold;
    }
    .body p { margin-bottom: 12pt; text-align: justify; }
    .closing { margin-top: 24pt; }
    .signature-line {
      margin-top: 48pt;
      border-top: 1px solid #333;
      width: 250px;
      padding-top: 4pt;
      font-size: 11pt;
      color: #555;
    }
    .footer {
      position: fixed;
      bottom: 0;
      left: 0;
      right: 0;
      text-align: center;
      font-size: 8pt;
      color: #999;
      padding: 0 1in;
    }
  </style>
</head>
<body>
  <div class="date">${dateStr}</div>

  <div class="recipient">
    ${data.filingBodyFull}<br>
    ${data.county} County<br>
    ${data.state === 'TX' ? 'Texas' : 'Illinois'}
  </div>

  <div class="subject">
    Re: ${data.taxYear} Property Tax Protest — Account #${data.acct}<br>
    Property: ${data.address}
  </div>

  <div class="body">
    <p>Dear Appraisal Review Board,</p>

    <p>
      I am writing to formally protest the ${data.taxYear} appraised value of my property located at
      <strong>${data.address}</strong> (Account #${data.acct}). The current appraised value of
      <strong>${formatCurrency(data.currentAssessment)}</strong> does not reflect the fair market value
      of this property based on comparable sales in the area.
    </p>

    <p>
      Based on my analysis of <strong>${data.compCount} comparable properties</strong> in the same
      neighborhood and market area, I believe the fair market value of my property is
      <strong>${formatCurrency(data.fairAssessment)}</strong>, representing a reduction of
      <strong>${formatCurrency(reduction)}</strong> (${data.overAssessedPct.toFixed(1)}% over-assessment).
    </p>

    <p>
      The current assessment values my property at <strong>$${data.perSqft.toFixed(2)}/sq ft</strong>,
      while the median comparable sale price is <strong>$${data.compMedianPerSqft.toFixed(2)}/sq ft</strong>.
      This discrepancy demonstrates that my property is assessed above what the market supports.
    </p>

    <p>
      I have attached a detailed evidence packet containing the comparable sales data supporting this
      protest. I respectfully request that the appraisal review board adjust the appraised value to
      reflect the true market conditions.
    </p>

    <p>
      Thank you for your time and consideration. I am available to discuss this matter further at
      the scheduled hearing or at your convenience.
    </p>
  </div>

  <div class="closing">
    <p>Respectfully,</p>
    <div class="signature-line">
      ${data.ownerName}<br>
      Property Owner
    </div>
  </div>

  <div class="footer">
    Generated by Overtaxed · getovertaxed.com · For informational purposes — verify details before filing
  </div>
</body>
</html>`;
}
